services:
  mineru:
    build: ./data_extraction/mineru
    ports:
      - "8000:8000"
    volumes:
      - "./data_extraction/tmp:/app/tmp"
      - "./data_extraction/data:/app/data"
    networks:
      - pc_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - HOST_IP=host.docker.internal

networks:
  pc_network:
    driver: bridge